version: 2

jobs:
  build:
    docker:
      - image: imos/icfpc2018:latest

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"

    steps:
      - checkout
      - setup_remote_docker:
        docker_layer_caching: true
      - restore_cache:
          key: project-cache
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: rustup run stable cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
